import React, { useEffect } from "react";
import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css";

export default function Home() {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  useEffect(() => {
    typeof document !== undefined
      ? require("bootstrap/dist/js/bootstrap")
      : null;
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>
          Ashfaq Mahmood Rafi || Front End Software Engineer | UX Designer
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          <div className="pro-pic dib">
            <Image
              className="profile-image img-responsive pull-left"
              src="/assets/images/rafi.jpg"
              alt="Rafi"
              width={500}
              height={500}
            />
          </div>

          <div className="profile-content pull-right dib">
            <h1 className="name">Ashfaq Mahmood</h1>
            <h2 className="desc">Front End Software Engineer | UX Designer</h2>
            <ul className="social list-inline">
              <li>
                <a
                  href="https://twitter.com/ashfaqrafi"
                  target="_blank"
                  rel="noreferrer"
                >
                  <i className="fa fa-twitter"></i>
                </a>
              </li>
              <li>
                <a
                  href="https://www.facebook.com/ashfaq.rafi"
                  target="_blank"
                  rel="noreferrer"
                >
                  <i className="fa fa-facebook"></i>
                </a>
              </li>
              <li>
                <a
                  href="https://www.linkedin.com/in/ashfaqrafi/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <i className="fa fa-linkedin"></i>
                </a>
              </li>
              <li>
                <a
                  href="https://github.com/ashfaqrafi"
                  target="_blank"
                  rel="noreferrer"
                >
                  <i className="fa fa-github-alt"></i>
                </a>
              </li>
              <li>
                <a
                  href="https://stackoverflow.com/users/6187671/ashfaqrafi"
                  target="_blank"
                  rel="noreferrer"
                >
                  <i className="fa fa-stack-overflow"></i>
                </a>
              </li>
              <li className="last-item">
                <a
                  href="https://www.behance.net/ashfaqrafi"
                  target="_blank"
                  rel="noreferrer"
                >
                  <i className="fa fa-behance-square"></i>
                </a>
              </li>
            </ul>
            <div>
              <a
                className="btn btn-cta-primary pull-right"
                href="http://www.ashfaqmahmood.net/blog/"
                target="_blank"
                rel="noreferrer"
              >
                Read My Blog
              </a>
              <a
                className="btn btn-cta-primary pull-right mr3"
                href="https://docs.google.com/document/d/1OUyTdFdx_d3fueJv6zi1IiBzUCXotN9LbH2ppU-ej78/edit"
                target="_blank"
                rel="noreferrer"
              >
                Resume
              </a>
            </div>
          </div>
        </div>
        <div className="container sections-wrapper">
          <div className="row">
            <div className="primary col-md-8 col-sm-12 col-xs-12">
              <section className="about section">
                <div className="section-inner">
                  <h2 className="heading">About Me</h2>
                  <div className="content">
                    <p>
                      Originally from Chittagong, Bangladesh, I am a Front End
                      Software Developer currently based in Dhaka, Bangladesh,
                      pursued my Bachelors in Computer Science and Engineering
                      degree at North South University, Dhaka, Bangladesh.
                    </p>

                    <p>
                      I always look forward to make web applications beautiful
                      and optimized using my skills in UI and UX development.
                      Making good friends, watching football, eating good foods
                      and enjoying music are most of my favorite activities
                      besides coding.
                    </p>
                  </div>
                </div>
              </section>

              <section className="latest section">
                <div className="section-inner">
                  <h2 className="heading">Projects</h2>
                  <div className="content">
                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://teachflex.inov.io/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/nt.jpeg"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://teachflex.inov.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            TEACHFLEX
                          </a>
                        </h3>
                        <p>
                          Nov 2016 – May 2017: TeachFlex aims to build a
                          Personalize experience into Education. Here a student
                          is directly connected to a teacher and
                          learning-teaching happens in a personalized way. A
                          student can enroll his chosen className with the
                          chosen faculty and the teaching takes place into the
                          Application itself, so that the student can learn from
                          anywhere and the teacher can teach remotely. It is an
                          excellent tool for distance learning.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: Node.js, Express.js, React, Redux,
                          PubNub, HTML, CSS, MongoDB
                        </p>
                        <p>
                          <span className="badge badge-danger mybadge">
                            Deprecated
                          </span>
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://teachflex.inov.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="http://collabhero.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/collab.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="http://collabhero.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            COLLABHERO
                          </a>
                        </h3>
                        <p>
                          May 2017 – Jun 2017: Collabhero is an online platform
                          where teachers can give assignments to the students
                          and the students will review and remark the
                          assignments by Peer or Group review.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: Python, Django, React, Redux, HTML,
                          CSS, MySQL
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="http://collabhero.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://localinsights.io/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/li.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://localinsights.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            LOCAL INSIGHTS
                          </a>
                        </h3>
                        <p>
                          Mar 2017 – Mar 2017: Local Insights ingests real time
                          data like new home purchases, home remodeling plans,
                          and divorce records so lenders can manage risk and
                          target a specific customer segment. We are a highly
                          skilled team of 28 people working on the newest
                          technologies with the best practices to ensure
                          accurate and timely.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: Node, Express, React, Redux, HTML,
                          CSS, MongoDB
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://localinsights.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>
                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="http://www.urbanchefs.ae/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/uc.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="http://www.urbanchefs.ae/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            URBANCHEFS
                          </a>
                        </h3>
                        <p>
                          Jul 2016 – Oct 2016: Urban Chefs is an online platform
                          that enables its users to locate professional cooks,
                          order foods and obtain culinary services.
                        </p>
                        <p className="fwb">
                          Technology Used: Node, Meteor, HTML, CSS, jQuery,
                          MongoDB, Android, iOS
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="http://www.urbanchefs.ae/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="http://dev.finwallet.bhabiz.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/fin.jpeg"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="http://dev.finwallet.bhabiz.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            FINPLATFORM
                          </a>
                        </h3>
                        <p>
                          Apr 2017 – Jun 2017: Its a SAAS product consists of
                          Web,Android and iOS app which provides financial
                          assistance as well as a e-commerce platform to the
                          users of a particular FinTech provider.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: Python, Django, HTML, CSS, React,
                          Redux, MySQL, Android, iOS
                        </p>
                        <p>
                          <span className="badge badge-danger mybadge">
                            Deprecated
                          </span>
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="http://dev.finwallet.bhabiz.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://www.sparkdeakin.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/spark.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://www.sparkdeakin.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            SPARK
                          </a>
                        </h3>
                        <p>
                          Aug 2016 – Sep 2016: Its a Wordpress site for the
                          entrepreneurial mentorship project named Spark for the
                          students of Deakin University,Melbourne,Australia{" "}
                        </p>
                        <p className="fwb">Technology Used: WordPress</p>
                        <p>
                          <a
                            className="more-link"
                            href="https://www.sparkdeakin.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://www.alemhealth.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/ah.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://www.alemhealth.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            ALEMHEALTH HUB
                          </a>
                        </h3>
                        <p>
                          Jul 2016 – Aug 2016: It is a product which is a part
                          of the Alemhealth project, in this app all the
                          facilities and providers of the Alemhealth app will be
                          connected with each other and they will be able to
                          share dicoms and reports with each other. This hub app
                          runs on a custom made device and chip which is using
                          Android OS. It works like a hub destination of the
                          stake holders using Alemhealth, CheckinLab and other
                          services of the Alemhealth project.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: Python, Django, HTML, CSS, Angular
                          1.x
                        </p>
                        <p>
                          <span className="badge badge-danger pbadge">
                            Private
                          </span>
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://www.alemhealth.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://www.alemhealth.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/ah.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://www.alemhealth.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            ALEMHEALTH CHECKINLAB
                          </a>
                        </h3>
                        <p>
                          May 2016: It is a Hybrid Meteor app which runs on a
                          custom made tablet with a Nvidia Tegra chip that is a
                          part of Alemhealth project, this app will help the
                          hospital receptionists to record patient data, nurses
                          to schedule tests,results and the doctors to keep
                          record of the patients disease history, see the test
                          results.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: Node, Meteor, HTML, CSS
                        </p>
                        <p>
                          <span className="badge badge-danger pbadge">
                            Private
                          </span>
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://www.alemhealth.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://dailyworks.inov.io/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/in.jpeg"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://www.alemhealth.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            DAILYWORKS
                          </a>
                        </h3>
                        <p>
                          Jun 2016 – Jul 2016: A web app integrated with Slack
                          to manage employees standups, attendance, average
                          working hours and few more metrics.
                        </p>
                        <p className="fwb">
                          Technology Used: Node, Meteor, HTML, CSS, Chart.js
                        </p>
                        <p>
                          <span className="badge badge-danger pbadge">
                            Private
                          </span>
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://dailyworks.inov.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://cramstack.com/index.html"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/cram.jpeg"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://cramstack.com/index.html"
                            target="_blank"
                            rel="noreferrer"
                          >
                            CRAMSTACK SITE
                          </a>
                        </h3>
                        <p>
                          Jul 2017: Its the official web page of Cramstack- A
                          Bangladesh based startup which provides: The Complete
                          Data Solution Platform For The Enterprise.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: HTML, CSS, Grunt, Bower, SASS,
                          Bootstrap 3
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://cramstack.com/index.html"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="http://kandd.inov.io/index.html"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/knd.png"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="http://kandd.inov.io/index.html"
                            target="_blank"
                            rel="noreferrer"
                          >
                            KHADAMA & DRAOIL
                          </a>
                        </h3>
                        <p>
                          Oct 2016: Its a web app to find out Maids and Drivers
                          around the world, through this app one can search for
                          maids and drivers from countries around the world,
                          this app takes care of the whole process for this from
                          choosing the individual to make the complete payment.{" "}
                        </p>
                        <p className="fwb">
                          Technology Used: HTML, CSS, Grunt, Bower, SASS,
                          Bootstrap 3
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="http://kandd.inov.io/index.html"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>

                    <div className="item row">
                      <a
                        className="col-md-4 col-sm-4 col-xs-12"
                        href="https://inov.io/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <Image
                          className="img-responsive project-image"
                          src="/assets/images/projects/in.jpeg"
                          alt="project name"
                          width={500}
                          height={500}
                        />
                      </a>
                      <div className="desc col-md-8 col-sm-8 col-xs-12">
                        <h3 className="title">
                          <a
                            href="https://inov.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            INOVIO SITE
                          </a>
                        </h3>
                        <p>June 2017: Official Landing page for Inovio </p>
                        <p className="fwb">
                          Technology Used: HTML, CSS, Grunt, Bower, SASS,
                          Bootstrap 3
                        </p>
                        <p>
                          <a
                            className="more-link"
                            href="https://inov.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <i className="fa fa-external-link"></i> Find out
                            more
                          </a>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </section>

              <section className="experience section">
                <div className="section-inner">
                  <h2 className="heading">Work Experience</h2>
                  <div className="content">
                    <div className="item">
                      <h3 className="title">
                        UX Designer -{" "}
                        <span className="place">
                          <a
                            href="http://www.theuserhub.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            Userhub
                          </a>
                        </span>{" "}
                        <span className="year">(July 2018 - Present)</span>
                      </h3>
                      <p>
                        Design and implement UI & UX features in projects using
                        HTML5, CSS3, Javascript, jQuery. Participate and oversee
                        in product development and give useful insights in the
                        design and development process following UX Design
                        methodology.
                      </p>
                    </div>
                    <div className="item">
                      <h3 className="title">
                        Front End Software Developer -{" "}
                        <span className="place">
                          <a
                            href="https://cramstack.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            Cramstack
                          </a>
                        </span>{" "}
                        <span className="year">(July 2017 - June 2018)</span>
                      </h3>
                      <p>
                        Design and implement UI & UX features in different kinds
                        of projects using React.js, Redux, HTML5, CSS3,
                        Javascript, jQuery. Participate in the product
                        development lifecycle and give useful insights in the
                        design and development process using my UX skills.
                      </p>
                    </div>
                    <div className="item">
                      <h3 className="title">
                        Associate Front End Engineer -{" "}
                        <span className="place">
                          <a
                            href="https://inov.io/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            Inovio
                          </a>
                        </span>{" "}
                        <span className="year">(March 2016 - June 2017)</span>
                      </h3>
                      <p>
                        Designed and developed the front end of web applications
                        using HTML5, CSS3, Bootstrap3, Grunt, Bower, Webpack,
                        React.js, SASS and to make sure a great UI & UX exposure
                        for the clients. Used Adobe Photoshop and Illustrator
                        for some design projects.
                      </p>
                    </div>
                  </div>
                </div>
              </section>
            </div>
            <div className="secondary col-md-4 col-sm-12 col-xs-12">
              <aside className="info aside section">
                <div className="section-inner">
                  <h2 className="heading sr-only">Basic Information</h2>
                  <div className="content">
                    <ul className="list-unstyled">
                      <li>
                        <i className="fa fa-map-marker"></i>
                        <span className="sr-only">Location:</span>Dhaka,
                        Bangladesh
                      </li>
                      <li>
                        <i className="fa fa-envelope-o"></i>
                        <span className="sr-only">Email:</span>
                        <a href="#">ashfaq.bd92@gmail.com</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </aside>

              <aside className="skills aside section">
                <div className="section-inner">
                  <h2 className="heading">Skills</h2>
                  <div className="content">
                    <p className="intro">
                      Having spent over 6 years, I learned things about Computer
                      Science. Here is a list of the skills I acquired in that
                      time.
                    </p>

                    <div className="skillset">
                      <div className="item">
                        <h3 className="level-title">HTML5, CSS3, SASS</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">User Experience Design</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">Javascript &amp; jQuery</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">React and Redux</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">Product Design</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">Project Management</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">Wordpress</h3>
                      </div>

                      <div className="item">
                        <h3 className="level-title">
                          Adobe Photoshop,Adobe Illustrator, Adobe xd
                        </h3>
                      </div>
                    </div>
                  </div>
                </div>
              </aside>

              <aside className="education aside section">
                <div className="section-inner">
                  <h2 className="heading">Education</h2>
                  <div className="content">
                    <div className="item">
                      <h3 className="title">
                        <i className="fa fa-graduation-cap"></i>&nbsp;BS in
                        Computer Science and Engineering
                      </h3>
                      <h4 className="university">
                        North South University
                        <span className="year">&nbsp;(2011-2015)</span>
                      </h4>
                    </div>
                  </div>
                </div>
              </aside>

              <aside className="education aside section">
                <div className="section-inner">
                  <h2 className="heading">Certification</h2>
                  <div className="content">
                    <div className="item">
                      <h3 className="title">
                        <i className="fa fa-graduation-cap"></i>&nbsp;Microsoft
                        Technology Associate: Software Development Fundamentals
                      </h3>
                      <h4 className="university">
                        Microsoft<span className="year">&nbsp;(2014)</span>
                      </h4>
                    </div>
                    <div className="item">
                      <h3 className="title">
                        <i className="fa fa-graduation-cap"></i>&nbsp;Certified
                        User Experience Designer
                      </h3>
                      <h4 className="university">
                        Userhub&nbsp;
                        <span className="year">&nbsp;(Feb 2017-Aug 2017)</span>
                      </h4>
                    </div>
                    <div className="item">
                      <h3 className="title">
                        <i className="fa fa-graduation-cap"></i>&nbsp;Certified
                        Graphic and User Interface Designer
                      </h3>
                      <h4 className="university">
                        Userhub&nbsp;
                        <span className="year">&nbsp;(Feb 2018-Aug 2018)</span>
                      </h4>
                    </div>
                  </div>
                </div>
              </aside>

              <aside className="languages aside section">
                <div className="section-inner">
                  <h2 className="heading">Languages</h2>
                  <div className="content">
                    <ul className="list-unstyled">
                      <li className="item">
                        <span className="title">
                          <strong>Bangla:</strong>
                        </span>
                        <br />
                        <span className="level">
                          Native Speaker <br className="visible-xs" />
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                        </span>
                      </li>
                      <li className="item">
                        <span className="title">
                          <strong>English:</strong>
                        </span>
                        <br />
                        <span className="level">
                          Professional Proficiency{" "}
                          <br className="visible-sm visible-xs" />
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star"></i>{" "}
                          <i className="fa fa-star-half"></i>
                        </span>
                      </li>
                    </ul>
                  </div>
                </div>
              </aside>

              <aside className="list conferences aside section">
                <div className="section-inner">
                  <h2 className="heading">Publications</h2>
                  <div className="content">
                    <div>
                      <p className="fwb">
                        1. &nbsp; A personalized music recommender service based
                        on Fuzzy Inference System
                      </p>
                      <p>Aug 25, 2016</p>
                      <p>IEEE</p>

                      <small className="copyright">
                        Publication URL:{" "}
                        <a
                          href="https://ieeexplore.ieee.org/document/7550757/"
                          target="_blank"
                          rel="noreferrer"
                        >
                          IEEXplore
                        </a>
                      </small>
                    </div>

                    <div className="mtop3">
                      <p className="fwb">
                        2. &nbsp; Application of Optimum Binning Technique in
                        Data Mining Approaches to Predict Students’ Final Grade
                        in a Course
                      </p>
                      <p>Jan 1, 2015</p>
                      <p>Springer International Publishing</p>

                      <small className="copyright">
                        Publication URL:{" "}
                        <a
                          href="https://link.springer.com/chapter/10.1007%2F978-3-319-13153-5_16"
                          target="_blank"
                          rel="noreferrer"
                        >
                          SpringerLink
                        </a>
                      </small>
                    </div>
                  </div>
                </div>
              </aside>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
